name: redux_cats_and_dogs
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.1.0-63.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  shimmer: ^3.0.0
  flutter_hooks: ^0.20.0
  firebase_auth: ^4.7.2
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/icons/